Repository googleapis/python-recaptcha-enterprise, pull requests merged in 2021-08, with the labels that each got.

#105 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: api: recaptchaenterprise, automerge, cla: yes

#109 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: automerge, cla: yes, api: recaptchaenterprise, samples

#114 chore: migrate default branch from master to main
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  owlbot.py
Labels: cla: yes, api: recaptchaenterprise
